[monitor:///opt/splunk/etc/apps/breachlens_splunk/sample_data/alerts.jsonl]
disabled = 0
index = breachlens
sourcetype = breachlens:alert

[monitor:///opt/splunk/etc/apps/breachlens_splunk/sample_data/auth.jsonl]
disabled = 0
index = breachlens
sourcetype = breachlens:auth

[monitor:///opt/splunk/etc/apps/breachlens_splunk/sample_data/cloud.jsonl]
disabled = 0
index = breachlens
sourcetype = breachlens:cloud

[monitor:///opt/splunk/etc/apps/breachlens_splunk/sample_data/edr.jsonl]
disabled = 0
index = breachlens
sourcetype = breachlens:edr

[monitor:///opt/splunk/etc/apps/breachlens_splunk/sample_data/proxy.jsonl]
disabled = 0
index = breachlens
sourcetype = breachlens:proxy

